.TH startmintlxde 1 "May 17, 2013" "startmintlxde"

.SH NAME
startmintlxde \-program for...

.SH SYNOPSIS
.B startmintlxde
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B startmintlxde
program. This program...
.PP
\fBstartmintlxde\fP is used to start the desktop session of LXDE.
By default it loads openbox, lxpanel, pcmanfm and lxsession.

.SH AUTHOR
Mateusz Łukasik <mati75@linuxmint.pl>
